config/routes.rb
ActionController::Routing::Routes.draw do |map|
  Mephisto::Routing.connect_with map
end

app/models/site.rb
require 'uri'
require 'mephisto/theme_root'

class Site < ActiveRecord::Base
  @@default_assigns = {}
  @@theme_path      = Object::THEME_ROOT
  cattr_reader :theme_path, :default_assigns

  cattr_accessor :multi_sites_enabled, :cache_sweeper_tracing
  
  # @@template_handlers = HashWithIndifferentAccess.new if @@template_handlers.nil?
  @@template_handlers = {}
  
  # Register a class that knows how to handle template files with the given
  # extension. This can be used to implement new template types.
  # The constructor for the class must take a Site instance
  # as a parameter, and the class must implement a #render method that
  # has the following signature
  # def render(section, layout, template, assigns ={}, controller = nil)
  # and return the rendered template as a string.
  def self.register_template_handler(extension, klass)
    @@template_handlers[extension] = klass
  end
  register_template_handler(".liquid", Mephisto::Liquid::LiquidTemplate)

  def self.extensions
    @@template_handlers.keys
  end

  has_many  :sections, :order => "position", :dependent => :destroy do
    def home
      find_by_path ''
    end

    # orders sections in a site
    def order!(*sorted_ids)
      transaction do
        sorted_ids.flatten.each_with_index do |section_id, pos|
          Section.update_all ['position = ?', pos], ['id = ? and site_id = ?', section_id, proxy_owner.id]
        end
      end
    end
  end

  has_many  :articles, :dependent => :destroy do
    def find_by_permalink(options)
      conditions = 
        returning ["(contents.published_at IS NOT NULL AND contents.published_at <= ?)", Time.now.utc] do |cond|
          if options[:year]
            from, to = Time.delta(options[:year], options[:month], options[:day])
            cond.first << ' AND (contents.published_at BETWEEN ? AND ?)'
            cond << from << to
          end
          
          [:id, :permalink].each do |attr|
            if options[attr]
              cond.first << " AND (contents.#{attr} = ?)"
              cond << options[attr]
            end
          end
        end
      
      find :first, :conditions => conditions, :order => 'published_at desc'
    end
  end
  
  has_many  :comments, :order => 'comments.created_at desc', :dependent => :delete_all
  
  has_many  :events, :dependent => :destroy
  
  has_many  :cached_pages, :dependent => :destroy
  
  has_many  :assets, :order => 'created_at desc', :conditions => 'parent_id is null', :dependent => :destroy

  has_many :memberships, :dependent => :destroy
  has_many :members, :through => :memberships, :source => :user
  has_many :admins,  :through => :memberships, :source => :user, :conditions => ['memberships.admin = ? or users.admin = ?', true, true]

  before_validation :downcase_host
  before_validation :set_default_attributes
  validates_presence_of :permalink_style, :search_path, :tag_path
  validates_format_of     :search_path, :tag_path, :with => Format::STRING
  validates_format_of     :host, :with => Format::DOMAIN
  validates_uniqueness_of :host
  validate :check_permalink_style
  
  after_create :setup_site_theme_directories
  after_create { |site| site.sections.create(:name => 'Home') }
  before_destroy :flush_cache_and_remove_site_directories    

  with_options :order => 'contents.created_at DESC', :class_name => 'Comment' do |comment|
    comment.has_many :comments,            :conditions => ['contents.approved = ?', true]
    comment.has_many :unapproved_comments, :conditions => ['contents.approved = ? or contents.approved is null', false]
    comment.has_many :all_comments
  end
  
  def self.search_by_host_or_title(search_string)
    conditions = search_string.blank? ? nil : ["host LIKE ? OR title LIKE ?"] + ["%#{search_string}%"] * 2
    with_scope( :find => { :conditions => conditions } ) do
      yield
    end
  end

  def users(options = {})
    User.find_all_by_site self, options
  end
  
  def users_with_deleted(options = {})
    User.find_all_by_site_with_deleted self, options
  end
  
  def user(id)
    User.find_by_site self, id
  end
  
  def user_with_deleted(id)
    User.find_by_site_with_deleted self, id
  end

  def user_by_token(token)
    User.find_by_token(self, token)
  end
  
  def user_by_email(email)
    User.find_by_email(self, email)
  end

  def tags
    Tag.find(:all, :select      => "DISTINCT tags.name",
                   :joins       => "INNER JOIN taggings ON taggings.tag_id = tags.id INNER JOIN contents ON (taggings.taggable_id = contents.id AND 
                                    taggings.taggable_type = 'Content')",
                   :conditions  => ['contents.type = ? AND contents.site_id = ?', 'Article', id],
                   :order       => 'tags.name')
  end

  def theme_path
    @theme_path ||= self.class.theme_path + "site-#{id}"
  end

  def attachment_path
    theme.path
  end

  def themes
    return @themes unless @themes.nil?
    @themes = []
    FileUtils.mkdir_p theme_path
    Dir.foreach theme_path do |e|
      next if e.first == '.'
      entry = theme_path + e
      next unless entry.directory?
      @themes << Theme.new(entry, self)
    end
    def @themes.[](key) key = key.to_s ; detect { |t| t.name == key } ; end
    @themes.sort! {|a,b| a.name <=> b.name}
  end

  def theme
    @theme ||= themes[current_theme_path] || themes.first || raise(MissingThemesError.new(self))
  end

  def change_theme_to(new_theme_path)
    new_theme = (new_theme_path.is_a?(Theme) ? new_theme_path : themes[new_theme_path]) || raise("No theme '#{new_theme_path}' found")
    update_attribute :current_theme_path, new_theme.path.basename.to_s
    @theme = nil
    theme
  end

  def import_theme(zip_file, name)
    imported_name = Theme.import zip_file, :to => theme_path + name
    @theme = @themes = @rollback_theme = nil
    themes[imported_name]
  end

  def move_theme(theme, new_name)
    FileUtils.move theme.base_path, theme_path + new_name
  end

  [:attachments, :templates, :resources].each { |m| delegate m, :to => :theme }

  def permalink_for(article)
    Mephisto::Dispatcher.build_permalink_with(permalink_style, article)
  end

  def search_url(query, page = nil)
    "/#{search_path}?q=#{CGI::escapeHTML(query)}#{%(&amp;page=#{CGI::escapeHTML(page.to_s)}) unless page.blank?}"
  end

  def tag_url(*tags)
    ['', tag_path, *tags.collect { |t| URI::escape(t.to_s) }] * '/' 
  end

  def accept_comments?
    comment_age.to_i > -1
  end

  def call_render(section, template_type, assigns = {}, controller = nil, options = {})
    assigns.update('site' => to_liquid(section), 'mode' => template_type)
    assigns.update(default_assigns) unless default_assigns.empty?
    options.reverse_merge!(:layout => true)
    template = set_content_template(section, template_type)
    handler = @@template_handlers[theme.extension] || @@template_handlers[".liquid"]
    
    if options[:layout]
      layout = set_layout_template(section, template_type)
      handler.new(self).render(section, layout, template, assigns, controller)
    else
      handler.new(self).parse_inner_template(template, assigns, controller)
    end
  end
  
  def to_liquid(current_section = nil)
    SiteDrop.new self, current_section
  end

  composed_of :timezone, :class_name => 'TZInfo::Timezone', :mapping => %w(timezone name)

  def timezone_name
    timezone.name
  end

  def timezone_name= name
    self.timezone = TZInfo::Timezone.new(name)
  end

  def page_cache_directory
    multi_sites_enabled ? 
      (RAILS_PATH + (RAILS_ENV == 'test' ? 'tmp' : 'public') + 'cache' + host) :
      (RAILS_PATH + (RAILS_ENV == 'test' ? 'tmp/cache' : 'public'))
  end

  def expire_cached_pages(controller, log_message, pages = nil)
    controller = controller.class unless controller.is_a?(Class)
    pages ||= cached_pages.find_current(:all)
    returning cached_log_message_for(log_message, pages) do |msg|
      controller.logger.warn msg if cache_sweeper_tracing
      pages.each { |p| controller.expire_page(p.url) }
      CachedPage.expire_pages(self, pages)
    end
  end

#need non protected method for ErbTemplate - psq
  def find_preferred_template(template_type, custom_template)
    preferred = templates.find_preferred(template_type, custom_template)
    return preferred if preferred && preferred.file?
    raise MissingTemplateError.new(template_type, templates.collect_templates(template_type, custom_template).collect(&:basename))
  end

  protected
    def cached_log_message_for(log_message, pages)
      pages.inject([log_message, "Expiring #{pages.size} page(s)"]) { |msg, p| msg << " - #{p.url}" }.join("\n")
    end
  
    def permalink_variable_format?(var)
      Mephisto::Dispatcher.variable_format?(var)
    end

    def permalink_variable?(var)
      Mephisto::Dispatcher.variable?(var)
    end

    def check_permalink_style
      permalink_style.sub! /\A\//, ''
      permalink_style.sub! /\/\z/, ''
      pieces = permalink_style.split('/')
      errors.add :permalink_style, 'cannot have blank paths' if pieces.any?(&:blank?)
      pieces.each do |p|
        errors.add :permalink_style, "cannot contain '#{p}' variable" unless p.blank? || permalink_variable_format?(p).nil? || permalink_variable?(p)
      end
      unless pieces.include?(':id') || pieces.include?(':permalink')
        errors.add :permalink_style, "must contain either :permalink or :id"
      end
      if !pieces.include?(':year') && (pieces.include?(':month') || pieces.include?(':day'))
        errors.add :permalink_style, "must contain :year for any date-based permalinks"
      end
    end

    def downcase_host
      self.host = host.to_s.downcase
    end

    def set_default_attributes
      self.permalink_style = ':year/:month/:day/:permalink' if permalink_style.blank?
      self.search_path     = 'search' if search_path.blank?
      self.tag_path        = 'tags'   if tag_path.blank?
      [:permalink_style, :search_path, :tag_path].each { |a| send(a).downcase! }

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
  FILTER_TYPES = %w(approved unapproved) unless const_defined?(:FILTER_TYPES)

  def status_icon
    @status_icon ||= { :unpublished => %w(orange bstop.gif),
                       :pending     => %w(yellow document.gif),
                       :published   => %w(green check.gif) }
  end

  def link_to_article(article)
    return '' unless article
    article.published? ?
      link_to(h(article.title), site.permalink_for(article)) :
      h(article.title)
  end

  def published_at_for(article)
    return 'not published' unless article && article.published?
    utc_to_local(article.published_at).to_ordinalized_s(article.published_at.year == Time.now.utc.year ? :stub : :mdy)
  end

  def valid_filter?(filter = params[:filter])
    FILTER_TYPES.include? filter
  end
  
  def has_excerpt?
    return false unless @article.excerpt 
    @article.excerpt.length > 0
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/admin/articles/_article.html.erb
<tr class="<%= article.status %>" id="article_<%= article.id %>">
  <td><%= image_tag "mephisto/icons/#{status_icon[article.status][1]}", :class => "#{status_icon[article.status][0]} icon", :title => "This article is #{article.status}", :alt => "#{article.status}" %></td>
  <td class="article_title"><%= link_to(h(article.title), {:action => 'edit', :id => article}) %></td>
  <td class="ccount">
    <% if article.comments.size == 0 %>
      none
    <% else %>
      <%= link_to article.comments.size.to_s.rjust(2, '0'), article_comments_path(article) %>
    <% end %>
  </td>
  <td><span class="date"><%= published_at_for article %></span></td>
  <td><%= article.published? ? link_to(image_tag('/images/mephisto/icons/24-zoom-in.png', :style => 'vertical-align: middle'), @site.permalink_for(article)) : '&nbsp;' %></td>
</tr>

app/views/admin/articles/_form.html.erb
<%= error_messages_for 'article' %>
<% @style = has_excerpt? ? "" : "display:none" %>
<!-- begin required fields -->
<div class="group">
  <dl>
    <dt><label for="article_title">Title</label></dt>
    <dd><%= form.text_field :title, :class => 'big'  %></dd>
    <dt id="x-lbl" style="<%= @style %>"><%= form.label :excerpt %> <span class="hint">(<%= link_to_function 'Hide', %(['x-lbl', 'x-body'].each(Element.toggle)) %>)</span></dt>
    <dd id="x-body" style="<%= @style %>"><%= form.text_area :excerpt, :rows => '8', :class => 'fat'  %></dd>
    <dt><label for="article_body">Write your article</label> <span class="hint">(<%= link_to_function 'Add an excerpt', %(['x-lbl', 'x-body'].each(Element.toggle)) %>)</span></dt>
    <dd><%= form.text_area :body, :class => 'fat', :rows => 25  %></dd>
    <dt><label for="article_tag">Tags</label> <span class="hint">Enter one or more tags separated by a comma or a space (for example, <em>"Web Dev" Tutorials</em> or <em>Web Dev, Tutorials</em>).</span></dt>
    <dd><%= form.text_field :tag %></dd>
  </dl>
</div>
<!-- /end required fields -->

<!-- begin optional fields -->
<dl id="article-optional">
  <dt><label for="article-draft">Save as Draft?</label></dt>
  <dd><label><%= check_box_tag :draft, '1', !@article.new_record? && !@published, :id => 'article-draft' %> Yes, save this article as a draft.</label></dd>
  <dt id="publish-date-lbl"<%= %( style="display:none") unless @article.new_record? || @published -%>><%= label_tag 'article_created_at', 'Publish on this date:' %></dt>
  <dd id="publish-date"<%= %( style="display:none") unless @article.new_record? || @published -%>>
    <%= form.datetime_select :published_at, 
          :start_year => (@article.published_at || Time.now.utc).year-1, :end_year => (Time.now.utc.year + 5), :order => [:month, :day, :year] %>
  </dd>
</dl>
<!-- /end optional fields -->

app/views/admin/articles/_page_nav.html.erb
<% @filter = params[:filter].to_s.humanize.downcase %>
<% content_for :action_nav do %>
<div id="page-nav">
  <ul id="act-nav" class="clear">
    <% if controller.controller_name == 'comments' && controller.action_name == 'index' && @comments.size > 0 -%>
      <li><%= link_to_remote h("Delete these #{@filter != 'all' ? @filter : ''} comments"), :confirm => "Are you sure you wish to delete all #{@filter != 'all' ? @filter : ''} comments?",
          :url => { :controller => 'comments', :action => 'destroy', :id => @article }, :with => "ArticleForm.getAvailableComments().toQueryString('comment')"
        %></li>
    <% end -%>
  <% if @article && (admin? || @article.user_id == current_user.id) && @article.comment_age != -1 -%>
    <li id="close-article-comments"><%= link_to_remote 'Close comments for this article', 
      :url => { :controller => 'admin/comments', :action => 'close', :id => @article } %></li>
  <% end -%>
  <% if controller.action_name == 'edit' -%>
    <li><%= link_to('Preview', {:action => 'show', :id => @article}, {:target => '_blank'}) %></li>
  <% end -%>
    <li id="select">
      <a class="trigger" id="cog" href="#">&nbsp;</a>
      <div id="optgroup" style="display: none">
        <ul id="options">
        <% unless @article.nil? || @article.new_record? -%>
          <li><%= link_to 'Edit this article', :controller => 'articles', :action => 'edit', :id => @article, :version => nil %></li>
        <% end -%>
        <% if @article && @article.comments.size > 0 && !(controller.controller_name == 'comments' && controller.action_name == 'index') -%>
          <li><%= link_to "View comments", :controller => 'comments', :action => 'index', :article_id => @article %></li>
        <% end %>
				<% if @article && (admin? || @article.user_id == current_user.id) -%>
					<li><%= link_to_remote 'Delete this article', :url => article_path(@article), :method => :delete, :confirm => 'Are you sure you want to delete this article?' %></li>
				<% end -%>
        </ul>
      </div>
    </li>
  </ul>
</div>

<div id="filter" class="manual">
  <ul class="clear">
    <li><a href="#">&nbsp;</a></li>
  </ul>
  <ul id="attributes">
    <% if @article && controller.controller_name == 'articles' && controller.action_name == 'edit' -%>
    <li><label for="search">Revision:</label></li>
    <li>
      <select name="filter" id="revisionnum">
        <option value="0">Newest</option>
        <%= options_from_collection_for_select @article.versions.reverse, :version, :version, params[:version].to_i %>
      </select>
    </li>
    <% end -%>
    <% if controller.controller_name == 'comments' && controller.action_name == 'index' -%>
    <li><label for="comments_view">Show comments:</label></li>
    <li>
      <select id="comments-view">
        <%= options_for_select ['All', 'Unapproved', 'Approved'], params[:filter].to_s.humanize %>
      </select>
    </li>
    <% end -%>
  </ul>
</div>
<% end unless @article && @article.new_record? && @article.comments.size == 0 -%>

app/views/admin/articles/_shared_options.html.erb
<div class="sgroup">
  <h3>Publish in these sections</h3>
  <ul class="slist">
    <% @sections.each do |section| %>
      <li>
        <%= check_box_tag 'article[section_ids][]', section.id, @article.has_section?(section), 
              :id => "article_section_ids_#{section.id}" %>
        <label for="article_section_ids_<%= section.id %>"><%=h section.name %></label>
      </li>
    <% end %>
  </ul>
</div>

<div class="sgroup" id="filetabs">
  <ul class="stabs">
    <li id="tab-latest"><a href="#latest-files" class="selected" title="Latest files uploaded">Latest</a></li>
    <li id="tab-attached"><a href="#attached-files" title="Attached Assets">Attached</a></li>
    <li id="tab-search"><a href="#search-files" title="Search for files">Search</a></li>
    <li id="tab-files"><a href="#upload-files" title="Upload new files">Upload</a></li>
    <li id="tab-bucket"><a href="#bucket" title="Upload new files">Bucket</a></li>
  </ul>
  
  <div id="tabpanels">
    <div class="tabpanel" id="latest-files">
      <ul id="latest-assets" class="asset-list">
        <%= render :partial => "admin/assets/widget", :collection => @assets, :locals => { :prefix => 'latest' } %>
      </ul>
    </div>
    <div class="tabpanel" id="attached-files" style="display:none;">
      <ul id="attached-assets" class="asset-list">
        <%= render :partial => "admin/assets/widget", :collection => @article.assets, :locals => { :prefix => 'attached' } %>
      </ul>
    </div>
    <div class="tabpanel" id="search-files" style="display:none;">
      <label for="q" style="font-weight:bold;padding: 5px 0;">
        Search by tag or title 
        <img id="spinner" src="/images/mephisto/spinner.gif" alt="spinner" style="display:none;vertical-align: middle" />
      </label>
      <input class="searchbox" type="text" size="30" name="q" id="search-files-q" />
      <input type="button" value="Search" onclick="TinyTab.callbacks['search-files']($F('search-files-q'))" />
      <ul id="search-assets" class="asset-list"></ul>
      <% javascript_tag do -%>
        // Don't save the entire article when the user presses enter.
        Event.observe('search-files-q', 'keypress', function (event) {
          if (event.keyCode == Event.KEY_RETURN) {
            Event.stop(event);
            TinyTab.callbacks['search-files']($F('search-files-q'))
          }
        });
      <% end -%>
    </div>
    <div class="tabpanel" id="upload-files" style="display:none;">
      <p>
        <strong>1.</strong>
        <%= file_field_tag 'asset[uploaded_data]', :size => 15, :id => 'asset_uploaded_data' %>
      </p>
      <p><strong>2.</strong> <input type="button" value="Upload" onclick="Asset.upload('article-form');" /></p>
    </div>
    <div class="tabpanel" id="bucket" style="display:none;">
      <ul id="bucket-assets" class="asset-list">
        <%= render :partial => "admin/assets/widget", :collection => @bucket_assets, :locals => { :prefix => 'bucket' } %>
      </ul>
    </div>
  </div>
  
</div>

<div class="sgroup">
  <h3>Optional settings</h3>
  <dl class="sform">
      <dt><label for="article_filter">Format with: </label></dt>
      <dd>
        <select name="article[filter]" id="article_filter">
        <%= options_for_select(filter_options, @article.filter) %>
      </select>
    </dd>
    <dt><label for="article_comment_age">Comments</label></dt>
    <dd><%= form.select :comment_age, comment_expiration_options %></dd>
    <dt><label for="article_permalink">Permanent link:</label></dt>
    <dd><%= form.text_field :permalink %></dd>
  </dl>
</div>

app/views/admin/articles/edit.html.erb
<%= render :partial => "page_nav" %>

<% fields_for :article, @version do |f| -%>
  <% content_for :sidebar do %>
    <%= render :partial => 'shared_options', :locals => { :form => f } %>
  <% end %>
<% end %>

<%= error_messages_for :article %>

<% content_for :form do -%>
  <%= form_tag({:action => 'update', :id => @article}, {:id => 'article-form', :multipart => true, :method => :put}) %>
<% end -%>

<% fields_for :article, @version do |f| -%>
  <%= render :partial => 'form', :object => f %>
  <p class="btns">
    <%= submit_tag 'Apply Changes' %>
    <%= submit_tag 'Save without Revision' %>
    <%= link_to "cancel", :controller => "articles" %>
  </p>
<% end -%>

app/views/admin/articles/index.html.erb
<% content_for :action_nav do %>
<!-- begin action nav -->
<div id="page-nav">
  <ul id="act-nav" class="clear">
    <li><%= link_to "Create new article", :action => "new" %></li>
  </ul>
</div>
<!-- /end action nav -->
<div id="filter" class="manual">
  <ul class="clear">
    <li><a href="#">&nbsp;</a></li>
  </ul>
  <% form_tag({:action => 'index'}, :method => 'get', :id => 'article-search') do -%>
  <ul id="attributes">
    <li><label for="search">Show articles:</label></li>
    <li>
      <select name="filter" id="filterlist">
        <%= options_for_select [
          ['in section',           'section'],
          ['tagged with',          'tags'],
          ['whose title contains', 'title'],
          ['whose body contains',  'body'],
          ['not published',        'draft']
        ] %>
      </select>
      <select name="section" id="sectionlist">
        <option value="0">&mdash;All Sections&mdash;</option>
        <%= options_from_collection_for_select @sections, :id, :name, params[:section].to_i %>
      </select>
    </li>
    <li><%= text_field_tag 'q', params[:q], :id => 'manualsearch', :style => 'display:none' %></li>
    <li><input type="button" id="searchsubmit" value="Go" style="display:none" /></li>
  </ul>
    <div><%= hidden_field_tag :published, 1 %></div>
  <% end -%>
</div>
<% end %>

<% if @articles.size > 0 -%>

<% content_tag :p, :class => 'total' do %>
  Total: <%= content_tag :strong, @articles.total_entries %> articles.
<% end %>

<!-- begin article list -->
<table id="article-list" cellspacing="0" cellpadding="0">
  <thead>
    <tr>
      <th scope="col" class="small-col">Status</th>
      <th scope="col">Article</th>
      <th scope="col">Comments</th>
      <th scope="col">Published</th>
      <th scope="col">&nbsp;</th>
    </tr>
  </thead>
  <tbody id="articles">
      <%= render :partial => 'article', :collection => @articles %>
  </tbody>
</table>
<!-- /end article list -->

<!-- begin pagination -->
<% if @articles.total_pages > 1 -%>
  <%= will_paginate @articles, :id => 'pagination' %>
<% end -%>
<!-- /end pagination -->

<% else %>
  <div class="empty" style="margin-bottom:20px">
    <% unless params[:filter] %>
      You have no articles.  <%= link_to "Create one now &raquo;", :action => "new" %>
    <% else %>
      You don't seem to have any articles matching that criteria.
    <% end %>
  </div>
<% end %>

<% content_for :sidebar do %>
  <% if @comments.any? -%>
  <div class="sgroup">
    <h3>Comments awaiting your approval</h3>
    <ul class="slist">
    <% @comments.each do |article, count| -%>
      <li><%= link_to "<strong>(#{count})</strong> #{h(article.title)}", article_comments_path(article), :filter => :unapproved %></li>
    <% end -%>
    </ul>
  </div>
  <% end -%>
<% end %>

app/views/admin/articles/new.html.erb
<% content_for :action_nav do -%>
  <div id="page-nav"></div>
<% end %>

<% fields_for :article do |f| -%>
<% content_for :sidebar do %>
  <%= render :partial => 'shared_options', :locals => { :form => f } %>
<% end %>
<% end %>

<% content_for :form do -%>
  <%= form_tag({:action => 'create'}, {:id => 'article-form', :multipart => true}) %>
<% end -%>

<% fields_for :article do |f| -%>
  <%= render :partial => 'form', :object => f %>
  
  <p class="btns">
    <%= submit_tag 'Save Article' %> or 
    <%= link_to "Cancel", :controller => "articles" %>
  </p>
<% end -%>